# Generated by Django 5.2 on 2026-01-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("cid", models.CharField(max_length=32)),
                ("hostname", models.CharField(max_length=200)),
                ("external_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("local_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(max_length=20)),
                ("platform_name", models.CharField(max_length=50)),
                ("os_version", models.CharField(max_length=50)),
                ("agent_version", models.CharField(max_length=50)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("system_manufacturer", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HostGroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("group_type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("assignment_rule", models.CharField(blank=True, max_length=200)),
                ("created_by", models.CharField(max_length=200)),
                ("created_timestamp", models.DateTimeField()),
                ("modified_by", models.CharField(max_length=200)),
                ("modified_timestamp", models.DateTimeField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceState",
            fields=[
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="online_state",
                        serialize=False,
                        to="api.device",
                    ),
                ),
                ("state", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="groups",
            field=models.ManyToManyField(related_name="devices", to="api.hostgroup"),
        ),
    ]
